production:
  adapter: postgresql
  database: prelaunchr_production
  host: localhost
development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost
